name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 'root'
        ports:
          - 1433:1433
        options: >-
          --health-cmd "timeout 1 bash -c '< /dev/tcp/localhost/1433' || exit 1"
          --health-interval 10s 
          --health-timeout 10s 
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for SQL Server
        run: |
          for i in {1..30}; do
            nc -z localhost 1433 && echo "SQL Server is ready!" && break
            echo "Waiting for SQL Server..." && sleep 5
          done

      - name: Initialize SQL Server Database
        run: |
          sqlcmd -S localhost -U sa -P root -Q "CREATE DATABASE myStore"

      - name: Run Tests
        run: mvn clean test

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t deepaksinghrathour/grocery-store:${{ github.sha }} .
          docker tag deepaksinghrathour/grocery-store:${{ github.sha }} deepaksinghrathour/grocery-store:latest
          docker push deepaksinghrathour/grocery-store:${{ github.sha }}
          docker push deepaksinghrathour/grocery-store:latest
