name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 'ComplexP@ssw0rd123!'
        ports:
          - 5433:1433
        options: >-
          --memory=2g 
          --cpus=2 
          --health-cmd "sqlcmd -S localhost,5433 -U sa -P ComplexP@ssw0rd123! -Q 'SELECT 1'"
          --health-interval 10s 
          --health-timeout 10s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install SQL Server Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Wait for SQL Server
        run: |
          for i in {1..60}; do
            /opt/mssql-tools/bin/sqlcmd -S localhost,5433 -U sa -P ComplexP@ssw0rd123! -Q "SELECT 1" && echo "SQL Server is ready!" && break
            echo "Waiting for SQL Server to be ready..." && sleep 5
          done

      - name: Fetch SQL Server Logs (if failure occurs)
        if: failure()
        run: |
          docker logs $(docker ps -q --filter ancestor=mcr.microsoft.com/mssql/server:2019-latest)

      - name: Initialize SQL Server Database
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost,5433 -U sa -P ComplexP@ssw0rd123! -Q "CREATE DATABASE myStore"

      - name: Run Tests
        run: mvn clean test

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t deepaksinghrathour/grocery-store:${{ github.sha }} .
          docker tag deepaksinghrathour/grocery-store:${{ github.sha }} deepaksinghrathour/grocery-store:latest
          docker push deepaksinghrathour/grocery-store:${{ github.sha }}
          docker push deepaksinghrathour/grocery-store:latest
